---
# Setup and start proxy container

- name: Get user home directory
  shell: "getent passwd {{ proxy_user }} | cut -d: -f6"
  register: user_home_result
  changed_when: false

- name: Generate squid configuration from template
  template:
    dest: "{{ user_home_result.stdout }}/squid.conf"
    src: squid.conf.j2
    mode: '0644'

- name: Create squid proxy container
  containers.podman.podman_container:
    name: "{{ proxy_container_name }}"
    image: "{{ proxy_image }}"
    state: started
    dns: "127.0.0.1"
    restart_policy: always
    network: host
    volumes:
      - "{{ user_home_result.stdout }}/squid.conf:/etc/squid/squid.conf:Z" 